export const DEMO_USERS = [
  {
    id: 'user-alice',
    name: 'Alice Johnson',
    phone: '+1 (555) 234-5678',
    bio: 'Product Designer @ ConnectX 🎨 • Building intuitive UIs',
    role: 'Product Designer',
    avatar: {
      id: 'av-alice',
      name: 'Alice',
      photo: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
      emoji: '👩‍🎨',
      bg: '#fdf2f8',
      color: '#db2777',
      gradient: 'linear-gradient(135deg, #ec4899 0%, #a855f7 100%)',
    },
    joinedAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    isOnline: true,
    isSystem: false,
  },
  {
    id: 'user-bob',
    name: 'Bob Smith',
    phone: '+1 (555) 876-5432',
    bio: 'Full Stack Architect ⚡ React & Node enthusiast',
    role: 'Lead Engineer',
    avatar: {
      id: 'av-bob',
      name: 'Bob',
      photo: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
      emoji: '👨‍💻',
      bg: '#eff6ff',
      color: '#2563eb',
      gradient: 'linear-gradient(135deg, #3b82f6 0%, #1d4ed8 100%)',
    },
    joinedAt: new Date(Date.now() - 86400000 * 10).toISOString(),
    isOnline: true,
    isSystem: false,
  },
  {
    id: 'user-charlie',
    name: 'Charlie Brown',
    phone: '+1 (555) 345-6789',
    bio: 'Product Growth & Marketing Lead 📈 Making magic happen',
    role: 'Growth Lead',
    avatar: {
      id: 'av-charlie',
      name: 'Charlie',
      photo: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=150&auto=format&fit=crop&q=80',
      emoji: '🧑‍💼',
      bg: '#ecfdf5',
      color: '#059669',
      gradient: 'linear-gradient(135deg, #10b981 0%, #047857 100%)',
    },
    joinedAt: new Date(Date.now() - 86400000 * 20).toISOString(),
    isOnline: true,
    isSystem: false,
  },
  {
    id: 'user-diana',
    name: 'Diana Prince',
    phone: '+1 (555) 987-6543',
    bio: 'Senior Program Manager 🚀 Connecting the dots',
    role: 'Program Manager',
    avatar: {
      id: 'av-diana',
      name: 'Diana',
      photo: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
      emoji: '👩‍💼',
      bg: '#fffbeb',
      color: '#d97706',
      gradient: 'linear-gradient(135deg, #f59e0b 0%, #b45309 100%)',
    },
    joinedAt: new Date(Date.now() - 86400000 * 30).toISOString(),
    isOnline: false,
    isSystem: false,
  },
];

export const INITIAL_BOT_USER = {
  id: 'user-connectx-bot',
  name: 'ConnectX AI',
  phone: '+1 (800) 555-0199',
  bio: 'Automated lounge assistant. Ready to connect and welcome everyone!',
  avatar: {
    id: 'avatar-bot',
    name: 'ConnectX AI',
    gradient: 'linear-gradient(135deg, #6d28d9 0%, #a855f7 100%)',
    emoji: '🤖',
    border: '#c084fc',
    bg: '#ede9fe',
    color: '#7c3aed',
  },
  joinedAt: new Date(Date.now() - 3600000 * 24).toISOString(),
  isOnline: true,
  isSystem: true,
};

export const INITIAL_GROUPS = [
  {
    id: 'general',
    name: '🚀 ConnectX Core Team',
    description: 'Central hub for all team announcements, feature updates, and discussions.',
    isGroup: true,
    avatar: {
      emoji: '🚀',
      bg: '#ede9fe',
      gradient: 'linear-gradient(135deg, #7c3aed 0%, #6366f1 100%)',
    },
    members: ['user-alice', 'user-bob', 'user-charlie', 'user-diana'],
    admins: ['user-alice', 'user-bob'],
    createdAt: new Date(Date.now() - 86400000 * 30).toISOString(),
  },
  {
    id: 'group_design',
    name: '🎨 Design & UI Squad',
    description: 'Figma mockups, design systems, tokens, and micro-interaction reviews.',
    isGroup: true,
    avatar: {
      emoji: '🎨',
      bg: '#fdf2f8',
      gradient: 'linear-gradient(135deg, #ec4899 0%, #8b5cf6 100%)',
    },
    members: ['user-alice', 'user-bob', 'user-diana'],
    admins: ['user-alice'],
    createdAt: new Date(Date.now() - 86400000 * 14).toISOString(),
  },
  {
    id: 'group_eng',
    name: '⚡ Frontend & Backend Tech',
    description: 'Architecture sync, real-time WebSockets, APIs, and performance benchmarking.',
    isGroup: true,
    avatar: {
      emoji: '⚡',
      bg: '#eff6ff',
      gradient: 'linear-gradient(135deg, #3b82f6 0%, #6366f1 100%)',
    },
    members: ['user-bob', 'user-charlie', 'user-alice'],
    admins: ['user-bob'],
    createdAt: new Date(Date.now() - 86400000 * 10).toISOString(),
  },
];

const now = Date.now();
const minutesAgo = (m) => new Date(now - m * 60000).toISOString();
const hoursAgo = (h) => new Date(now - h * 3600000).toISOString();
const daysAgo = (d) => new Date(now - d * 86400000).toISOString();

export const INITIAL_MESSAGES = [
  // General Group Messages
  {
    id: 'msg_gen_1',
    senderId: 'user-alice',
    senderName: 'Alice Johnson',
    senderAvatar: DEMO_USERS[0].avatar,
    text: 'Hey everyone! Welcome to ConnectX. We are putting the final touches on our real-time messaging UI! ✨',
    room: 'general',
    status: 'read',
    createdAt: daysAgo(1),
  },
  {
    id: 'msg_gen_2',
    senderId: 'user-bob',
    senderName: 'Bob Smith',
    senderAvatar: DEMO_USERS[1].avatar,
    text: 'WebSocket connection and optimistic UI updates are working with near zero latency 🚀 Check out the responsive layout!',
    room: 'general',
    status: 'read',
    createdAt: hoursAgo(4),
  },
  {
    id: 'msg_gen_3',
    senderId: 'user-charlie',
    senderName: 'Charlie Brown',
    senderAvatar: DEMO_USERS[2].avatar,
    text: 'Love the distinct sender and receiver perspective styling! It looks super crisp on mobile too.',
    mediaUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop&q=80',
    mediaType: 'image',
    room: 'general',
    status: 'read',
    createdAt: hoursAgo(2),
  },
  {
    id: 'msg_gen_4',
    senderId: 'user-alice',
    senderName: 'Alice Johnson',
    senderAvatar: DEMO_USERS[0].avatar,
    text: 'You can switch between users using the top perspective switcher to preview incoming vs outgoing bubbles in real time! 🙌',
    room: 'general',
    status: 'read',
    createdAt: minutesAgo(25),
  },

  // Design Group Messages
  {
    id: 'msg_des_1',
    senderId: 'user-alice',
    senderName: 'Alice Johnson',
    senderAvatar: DEMO_USERS[0].avatar,
    text: 'Here are the design tokens for our dark & light themes. Glassmorphism cards and tailored violet accents!',
    room: 'group_design',
    status: 'read',
    createdAt: daysAgo(2),
  },
  {
    id: 'msg_des_2',
    senderId: 'user-bob',
    senderName: 'Bob Smith',
    senderAvatar: DEMO_USERS[1].avatar,
    text: 'Tailwind CSS classes mapped perfectly. Animations feel completely native and fluid.',
    room: 'group_design',
    status: 'read',
    createdAt: hoursAgo(6),
  },

  // Direct Messages: Alice <-> Bob
  {
    id: 'msg_dm_ab_1',
    senderId: 'user-alice',
    senderName: 'Alice Johnson',
    senderAvatar: DEMO_USERS[0].avatar,
    text: 'Hi Bob! Have you checked the read receipt ticks on the outgoing bubbles?',
    room: 'dm_user-alice_user-bob',
    status: 'read',
    createdAt: hoursAgo(5),
  },
  {
    id: 'msg_dm_ab_2',
    senderId: 'user-bob',
    senderName: 'Bob Smith',
    senderAvatar: DEMO_USERS[1].avatar,
    text: 'Yes! Double checkmarks turn indigo when read, and incoming messages show avatar and sender header.',
    room: 'dm_user-alice_user-bob',
    status: 'read',
    createdAt: hoursAgo(1),
  },
  {
    id: 'msg_dm_ab_3',
    senderId: 'user-alice',
    senderName: 'Alice Johnson',
    senderAvatar: DEMO_USERS[0].avatar,
    text: 'Awesome. Try switching to my view or Charlie to test replying from both ends!',
    room: 'dm_user-alice_user-bob',
    status: 'delivered',
    createdAt: minutesAgo(10),
  },

  // Direct Messages: Bob <-> Charlie
  {
    id: 'msg_dm_bc_1',
    senderId: 'user-charlie',
    senderName: 'Charlie Brown',
    senderAvatar: DEMO_USERS[2].avatar,
    text: 'Bob, we should showcase the group creation modal with user checkboxes in the demo recording.',
    room: 'dm_user-bob_user-charlie',
    status: 'read',
    createdAt: hoursAgo(3),
  },
  {
    id: 'msg_dm_bc_2',
    senderId: 'user-bob',
    senderName: 'Bob Smith',
    senderAvatar: DEMO_USERS[1].avatar,
    text: 'Absolutely! The modal filters contacts in real-time and updates the group list instantly.',
    room: 'dm_user-bob_user-charlie',
    status: 'read',
    createdAt: minutesAgo(40),
  },
];
